package files;

public class Payload {
	
	
	
	public static String addPlace() {
		
	return "{\r\n"
			+ "  \"location\": {\r\n"
			+ "    \"lat\": -38.383494,\r\n"
			+ "    \"lng\": 33.427362\r\n"
			+ "  },\r\n"
			+ "  \"accuracy\": 50,\r\n"
			+ "  \"name\": \"Dhanush house\",\r\n"
			+ "  \"phone_number\": \"(+91) 983 893 3937\",\r\n"
			+ "  \"address\": \"29, side layout, cohen 09\",\r\n"
			+ "  \"types\": [\r\n"
			+ "    \"shoe park\",\r\n"
			+ "    \"shop\"\r\n"
			+ "  ],\r\n"
			+ "  \"website\": \"http://google.com\",\r\n"
			+ "  \"language\": \"French-IN\"\r\n"
			+ "}";
		
	}
	
	public static String MockComplexJson() {
		
		return "{\r\n"
				+ "\r\n"
				+ "\"dashboard\": {\r\n"
				+ "\r\n"
				+ "\"purchaseAmount\": 910,\r\n"
				+ "\r\n"
				+ "\"website\": \"rahulshettyacademy.com\"\r\n"
				+ "\r\n"
				+ "},\r\n"
				+ "\r\n"
				+ "\"courses\": [\r\n"
				+ "\r\n"
				+ "{\r\n"
				+ "\r\n"
				+ "\"title\": \"Selenium Python\",\r\n"
				+ "\r\n"
				+ "\"price\": 50,\r\n"
				+ "\r\n"
				+ "\"copies\": 6\r\n"
				+ "\r\n"
				+ "},\r\n"
				+ "\r\n"
				+ "{\r\n"
				+ "\r\n"
				+ "\"title\": \"Cypress\",\r\n"
				+ "\r\n"
				+ "\"price\": 40,\r\n"
				+ "\r\n"
				+ "\"copies\": 4\r\n"
				+ "\r\n"
				+ "},\r\n"
				+ "\r\n"
				+ "{\r\n"
				+ "\r\n"
				+ "\"title\": \"RPA\",\r\n"
				+ "\r\n"
				+ "\"price\": 45,\r\n"
				+ "\r\n"
				+ "\"copies\": 10\r\n"
				+ "\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "]\r\n"
				+ "\r\n"
				+ "}";
	}
	
	
	
	
	public static String dynamicParameterization() {
		
		String dynamicPara="{\r\n"
				+ "	\"info\": {\r\n"
				+ "		\"_postman_id\": \"5e6418be-ecd1-49f9-941a-a8d6a47ee5a4\",\r\n"
				+ "		\"name\": \"Library API\",\r\n"
				+ "		\"schema\": \"https://schema.getpostman.com/json/collection/v2.1.0/collection.json\"\r\n"
				+ "	},\r\n"
				+ "	\"item\": [\r\n"
				+ "		{\r\n"
				+ "			\"name\": \"Add Book\",\r\n"
				+ "			\"request\": {\r\n"
				+ "				\"method\": \"POST\",\r\n"
				+ "				\"header\": [],\r\n"
				+ "				\"body\": {\r\n"
				+ "					\"mode\": \"raw\",\r\n"
				+ "					\"raw\": \"{\\n\\\"name\\\":\\\"Learn Appium Automation with Java\\\",\\n\\\"isbn\\\":\\\"bcd\\\",\\n\\\"aisle\\\":\\\"2926\\\",\\n\\\"author\\\":\\\"John foer\\\"\\n}\\n\"\r\n"
				+ "				},\r\n"
				+ "				\"url\": {\r\n"
				+ "					\"raw\": \"https://rahulshettyacademy.com/Library/Addbook.php\",\r\n"
				+ "					\"protocol\": \"https\",\r\n"
				+ "					\"host\": [\r\n"
				+ "						\"rahulshettyacademy\",\r\n"
				+ "						\"com\"\r\n"
				+ "					],\r\n"
				+ "					\"path\": [\r\n"
				+ "						\"Library\",\r\n"
				+ "						\"Addbook.php\"\r\n"
				+ "					]\r\n"
				+ "				}\r\n"
				+ "			},\r\n"
				+ "			\"response\": []\r\n"
				+ "		},\r\n"
				+ "		{\r\n"
				+ "			\"name\": \"Get Book By ID\",\r\n"
				+ "			\"request\": {\r\n"
				+ "				\"method\": \"GET\",\r\n"
				+ "				\"header\": [],\r\n"
				+ "				\"url\": {\r\n"
				+ "					\"raw\": \"https://rahulshettyacademy.com/Library/GetBook.php?ID=bcd2926\",\r\n"
				+ "					\"protocol\": \"https\",\r\n"
				+ "					\"host\": [\r\n"
				+ "						\"rahulshettyacademy\",\r\n"
				+ "						\"com\"\r\n"
				+ "					],\r\n"
				+ "					\"path\": [\r\n"
				+ "						\"Library\",\r\n"
				+ "						\"GetBook.php\"\r\n"
				+ "					],\r\n"
				+ "					\"query\": [\r\n"
				+ "						{\r\n"
				+ "							\"key\": \"ID\",\r\n"
				+ "							\"value\": \"bcd2926\"\r\n"
				+ "						}\r\n"
				+ "					]\r\n"
				+ "				}\r\n"
				+ "			},\r\n"
				+ "			\"response\": []\r\n"
				+ "		},\r\n"
				+ "		{\r\n"
				+ "			\"name\": \"Get Book By Author Name\",\r\n"
				+ "			\"request\": {\r\n"
				+ "				\"method\": \"GET\",\r\n"
				+ "				\"header\": [],\r\n"
				+ "				\"url\": {\r\n"
				+ "					\"raw\": \"https://rahulshettyacademy.com/Library/GetBook.php?AuthorName=John foer\",\r\n"
				+ "					\"protocol\": \"https\",\r\n"
				+ "					\"host\": [\r\n"
				+ "						\"rahulshettyacademy\",\r\n"
				+ "						\"com\"\r\n"
				+ "					],\r\n"
				+ "					\"path\": [\r\n"
				+ "						\"Library\",\r\n"
				+ "						\"GetBook.php\"\r\n"
				+ "					],\r\n"
				+ "					\"query\": [\r\n"
				+ "						{\r\n"
				+ "							\"key\": \"AuthorName\",\r\n"
				+ "							\"value\": \"John foer\"\r\n"
				+ "						}\r\n"
				+ "					]\r\n"
				+ "				}\r\n"
				+ "			},\r\n"
				+ "			\"response\": []\r\n"
				+ "		},\r\n"
				+ "		{\r\n"
				+ "			\"name\": \"Delete Book\",\r\n"
				+ "			\"request\": {\r\n"
				+ "				\"method\": \"DELETE\",\r\n"
				+ "				\"header\": [],\r\n"
				+ "				\"body\": {\r\n"
				+ "					\"mode\": \"raw\",\r\n"
				+ "					\"raw\": \"{\\n    \\\"ID\\\": \\\"bcd2926\\\"\\n}\"\r\n"
				+ "				},\r\n"
				+ "				\"url\": {\r\n"
				+ "					\"raw\": \"https://rahulshettyacademy.com//Library/DeleteBook.php\",\r\n"
				+ "					\"protocol\": \"https\",\r\n"
				+ "					\"host\": [\r\n"
				+ "						\"rahulshettyacademy\",\r\n"
				+ "						\"com\"\r\n"
				+ "					],\r\n"
				+ "					\"path\": [\r\n"
				+ "						\"\",\r\n"
				+ "						\"Library\",\r\n"
				+ "						\"DeleteBook.php\"\r\n"
				+ "					]\r\n"
				+ "				}\r\n"
				+ "			},\r\n"
				+ "			\"response\": []\r\n"
				+ "		}\r\n"
				+ "	]\r\n"
				+ "}";
				
				return dynamicPara;
		
	}
	

}



